### ISSUE TITLE
Add content in text format

### ISSUE THREAD

**Issue by ctodea** [VladdyC/btctkvr-mag-3-2023#4]
Would it be possible to have a `src` or `txt` or similar folder with the content of each page as text only?

Would made tasks like translations way easier, copying text from a JPG or trying to extract it with an AI tool is very time consuming,

If done, translations could be submitted as new text files eg.: `src/en` could contain the english version, `src/es` the spanish one, etc,
1 file per page would work.
And then the translated versions could have something like:

```
# page_1.txt
# text in english
translated text
```

And that might also serve as guide for generating the JPGs in a diff language. Otherwise, how does the graphical designer know exactly where to put what?

**Comment by ctodea** [comment]
@VladdyC 👀

**Comment by ctodea** [comment]
Will take the text out of the magazine's site:
e.g.: https://bitcoin-takeover.com/breaking-fud-embracing-bitcoin/

**Comment by VladdyC** [comment]
This is a really great proposal, I'll definitely create separate text files for every article... to the very least.

The reason I haven't done this is that nobody else requested it.

**Comment by ctodea** [comment]
I'm not the fastest translating ([proof is I've only progressed on the prologue](https://github.com/ctodea/btctkvr-mag-3-2023-es)), last weeks I've been pretty busy, but having this would definitely make it easier for me.
